export const LABOR_CERT_VALIDITY_DAYS = 90;

/** Por debajo de esto sí se bloquea por ilegibilidad extrema */
export const LABOR_CERT_CRITICAL_MIN_WIDTH = 400;
export const LABOR_CERT_CRITICAL_MIN_HEIGHT = 280;

export const MIN_LABOR_CERT_KEYWORD_MATCHES = 2;

export const MIN_AUTHENTICITY_SIGNALS = 2;

export const LABOR_CERT_VALIDATION_TIMEOUT_MS = 120_000;

export const LABOR_CERT_KEYWORDS = [
  "CERTIFICACION LABORAL",
  "CERTIFICADO LABORAL",
  "CONSTANCIA LABORAL",
  "RECURSOS HUMANOS",
  "TALENTO HUMANO",
  "GESTION HUMANA",
  "CERTIFICA QUE",
  "VINCULACION LABORAL",
  "TRABAJA EN",
  "LABORA EN",
  "HACE CONSTAR",
] as const;

export const AUTHENTICITY_KEYWORDS = [
  "FIRMA",
  "SELLO",
  "MEMBRETE",
  "CODIGO QR",
  "CODIGO DE VALIDACION",
  "VALIDACION",
  "CORREO",
  "@",
  "WWW",
  "HTTP",
  "NIT",
  "GERENTE",
  "DIRECTOR",
  "REPRESENTANTE LEGAL",
  "JEFE DE",
] as const;
